version: "2.0"
services:
  web:
    image: nginx:1.13.3-alpine
    volumes:
      - ./static:/var/www/html/static
      - ./devops/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./devops/fastcgi_params:/etc/nginx/fastcgi_params
    ports:
      - 80:80
    links:
      - command
  command:
    image: php:7.1.5-cqrs
    build:
      context: ./devops
      dockerfile: Dockerfile
    volumes:
      - ./command:/app
      - ./devops/php-logs.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    working_dir: /app
    links:
      - db
  query:
    image: php:7.1.5-cqrs
    build:
      context: ./devops
      dockerfile: Dockerfile
    volumes:
      - ./query:/app
      - ./devops/php-logs.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    working_dir: /app
    links:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cqrs
      - MYSQL_USER=cqrs
      - MYSQL_PASSWORD=cqrs
    volumes:
      - .data/db/:/var/lib/mysql
