version: "2.0"
services:
  command:
    image: php:7.1.5-cqrs
    build:
      context: ./devops
      dockerfile: Dockerfile
    volumes:
      - ./command:/app
    working_dir: /app
    command: ./composer.phar run serve --timeout=0
    ports:
      - 8080:8080
    links:
      - db
  query:
    image: php:7.1.5-cqrs
    build:
      context: ./devops
      dockerfile: Dockerfile
    volumes:
      - ./query:/app
    working_dir: /app
    command: ./composer.phar run serve --timeout=0
    ports:
      - 8081:8080
    links:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cqrs
      - MYSQL_USER=cqrs
      - MYSQL_PASSWORD=cqrs
    volumes:
      - .data/db/:/var/lib/mysql
